<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="js/materialize.js"></script>
<script src="js/classie.js"></script>
<script src="js/demo12.js"></script>
<script src="js/init.js"></script>
<script src="js/owl.carousel.js"></script>
<script src="js/code.js"></script>
<script src="js/prism.js"></script>
